<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="images\exhale.png" />
    <None Remove="images\ferret.png" />
    <None Remove="images\ferret_stress_1.png" />
    <None Remove="images\ferret_stress_2.png" />
    <None Remove="images\ferret_stress_3.png" />
    <None Remove="images\holdbreath1.png" />
    <None Remove="images\holdbreath2.png" />
    <None Remove="images\inhale.png" />
    <None Remove="images\journal.png" />
    <None Remove="images\room.png" />
    <None Remove="images\treat.png" />
    <None Remove="images\wind_room.png" />
    <None Remove="UserData\biometrics.xml" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="images\exhale.png" />
    <Resource Include="images\ferret.png" />
    <Resource Include="images\ferret_pet_3.png" />
    <Resource Include="images\ferret_pet_4.png" />
    <Resource Include="images\ferret_play_0.png" />
    <Resource Include="images\ferret_pet_1.png" />
    <Resource Include="images\ferret_pet_2.png" />
    <Resource Include="images\ferret_stress_1.png" />
    <Resource Include="images\ferret_stress_2.png" />
    <Resource Include="images\ferret_stress_3.png" />
    <Resource Include="images\holdbreath1.png" />
    <Resource Include="images\holdbreath2.png" />
    <Resource Include="images\inhale.png" />
    <Resource Include="images\journal.png" />
    <Resource Include="images\room.png" />
    <Resource Include="images\treat.png" />
    <Resource Include="images\wind_room.png" />
    <Resource Include="UserData\Biometrics.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
